#!/usr/bin/env python3
"""
json_to_c.py: Translate bdd pattern JSON explanations to packed C99 struct definitions.

Usage:
    bdd --explain-pattern "sync:8u,te:1b,pusi:1b,pid:13u,payload:1472U" --output-json | python3 json_to_c.py --name MpegTsHeader
    python3 json_to_c.py input.json --name MyPacket > packet.h
"""

import sys
import json
import argparse
import math

C_KEYWORDS = {
    "auto", "break", "case", "char", "const", "continue", "default", "do", "double",
    "else", "enum", "extern", "float", "for", "goto", "if", "inline", "int", "long",
    "register", "restrict", "return", "short", "signed", "sizeof", "static", "struct",
    "switch", "typedef", "union", "unsigned", "void", "volatile", "while",
}


def sanitize_c_ident(name, idx):
    if not name or not name.strip():
        return f"field_{idx}"
    raw = name.strip()
    cleaned = []
    for i, c in enumerate(raw):
        if c.isalnum() or c == '_':
            if i == 0 and c.isdigit():
                cleaned.append('_')
            cleaned.append(c.lower())
        else:
            cleaned.append('_')
    ident = "".join(cleaned)
    if not ident:
        return f"field_{idx}"
    if ident in C_KEYWORDS:
        return f"_{ident}"
    return ident


def generate_c(data, struct_name="BddPacket"):
    pattern = data.get("pattern", "unknown")
    total_bits = data.get("total_bits", 0)
    total_bytes = data.get("total_bytes", total_bits / 8.0)
    fields = data.get("fields", [])

    guard = f"BDD_GENERATED_{struct_name.upper()}_H"

    lines = [
        "/* Generated by bdd json_to_c translator */",
        f"/* Pattern: {pattern} ({total_bits} bits, {total_bytes:.3f} bytes) */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "",
        "#pragma pack(push, 1)",
        f"typedef struct {{",
    ]

    for f in fields:
        idx = f.get("index", 0)
        name = f.get("name")
        char_code = f.get("char_code", "u")
        type_name = f.get("type_name", "")
        bits = f.get("bits", 8)
        bit_start = f.get("bit_start", 0)
        bit_end = f.get("bit_end", bit_start + bits - 1)
        byte_range = f.get("byte_range", "")

        ident = sanitize_c_ident(name, idx)
        bit_info = f"/* bits [{bit_start}..{bit_end}] ({bits} bits, {byte_range}) - {type_name} */"

        # Match type declarations
        if char_code in ('C', 'c') and bits % 8 == 0 and bits > 8:
            decl = f"char {ident}[{bits // 8}];"
        elif char_code in ('C', 'c') and bits == 8:
            decl = f"char {ident};"
        elif char_code in ('F', 'f') and bits == 32:
            decl = f"float {ident};"
        elif char_code in ('D', 'd') and bits == 64:
            decl = f"double {ident};"
        elif char_code in ('S', 's'):
            if bits == 8:
                decl = f"int8_t {ident};"
            elif bits == 16:
                decl = f"int16_t {ident};"
            elif bits == 32:
                decl = f"int32_t {ident};"
            elif bits == 64:
                decl = f"int64_t {ident};"
            elif bits <= 8:
                decl = f"int8_t {ident} : {bits};"
            elif bits <= 16:
                decl = f"int16_t {ident} : {bits};"
            elif bits <= 32:
                decl = f"int32_t {ident} : {bits};"
            elif bits <= 64:
                decl = f"int64_t {ident} : {bits};"
            elif bits % 8 == 0:
                decl = f"int8_t {ident}[{bits // 8}];"
            else:
                decl = f"int8_t {ident}[{math.ceil(bits / 8)}];"
        else:
            if bits == 8:
                decl = f"uint8_t {ident};"
            elif bits == 16:
                decl = f"uint16_t {ident};"
            elif bits == 32:
                decl = f"uint32_t {ident};"
            elif bits == 64:
                decl = f"uint64_t {ident};"
            elif bits <= 8:
                decl = f"uint8_t {ident} : {bits};"
            elif bits <= 16:
                decl = f"uint16_t {ident} : {bits};"
            elif bits <= 32:
                decl = f"uint32_t {ident} : {bits};"
            elif bits <= 64:
                decl = f"uint64_t {ident} : {bits};"
            elif bits % 8 == 0:
                decl = f"uint8_t {ident}[{bits // 8}];"
            else:
                decl = f"uint8_t {ident}[{math.ceil(bits / 8)}];"

        lines.append(f"    {decl:<28} {bit_info}")

    lines.append(f"}} {struct_name};")
    lines.append("#pragma pack(pop)")
    lines.append("")
    lines.append(f"#endif /* {guard} */")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Convert bdd pattern JSON to C struct definition")
    parser.add_argument("input", nargs="?", default="-", help="Input JSON file or '-' for stdin")
    parser.add_argument("-n", "--name", default="BddPacket", help="C struct name (default: BddPacket)")
    args = parser.parse_args()

    if args.input == "-":
        content = sys.stdin.read()
    else:
        with open(args.input, "r", encoding="utf-8") as f:
            content = f.read()

    data = json.loads(content)
    print(generate_c(data, struct_name=args.name), end="")


if __name__ == "__main__":
    main()
