#!/usr/bin/env python3
"""
json_to_rust.py: Translate bdd pattern JSON explanations to packed Rust struct definitions.

Usage:
    bdd --explain-pattern "sync:8u,te:1b,pusi:1b,pid:13u,payload:1472U" --output-json | python3 json_to_rust.py --name MpegTsHeader
    python3 json_to_rust.py input.json --name MyPacket > packet.rs
"""

import sys
import json
import argparse
import math

RUST_KEYWORDS = {
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn",
    "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
    "return", "self", "Self", "static", "struct", "super", "trait", "true", "type",
    "unsafe", "use", "where", "while", "async", "await", "dyn",
}


def sanitize_rust_ident(name, idx):
    if not name or not name.strip():
        return f"field_{idx}"
    raw = name.strip()
    cleaned = []
    for i, c in enumerate(raw):
        if c.isalnum() or c == '_':
            if i == 0 and c.isdigit():
                cleaned.append('_')
            cleaned.append(c.lower())
        else:
            cleaned.append('_')
    ident = "".join(cleaned)
    if not ident:
        return f"field_{idx}"
    if ident in RUST_KEYWORDS:
        return f"r#{ident}"
    return ident


def generate_rust(data, struct_name="BddPacket"):
    pattern = data.get("pattern", "unknown")
    total_bits = data.get("total_bits", 0)
    total_bytes = data.get("total_bytes", total_bits / 8.0)
    fields = data.get("fields", [])

    lines = [
        "// Generated by bdd json_to_rust translator",
        f"// Pattern: {pattern} ({total_bits} bits, {total_bytes:.3f} bytes)",
        "",
        "#[repr(C, packed)]",
        "#[derive(Debug, Clone, Copy, PartialEq)]",
        f"pub struct {struct_name} {{",
    ]

    for f in fields:
        idx = f.get("index", 0)
        name = f.get("name")
        char_code = f.get("char_code", "u")
        type_name = f.get("type_name", "")
        bits = f.get("bits", 8)
        bit_start = f.get("bit_start", 0)
        bit_end = f.get("bit_end", bit_start + bits - 1)
        byte_range = f.get("byte_range", "")

        ident = sanitize_rust_ident(name, idx)
        bit_info = f"// bits [{bit_start}..{bit_end}] ({bits} bits, {byte_range}) - {type_name}"

        # Match type declarations
        if char_code in ('F', 'f') and bits == 32:
            type_decl = "f32"
        elif char_code in ('D', 'd') and bits == 64:
            type_decl = "f64"
        elif char_code in ('S', 's'):
            if bits == 8:
                type_decl = "i8"
            elif bits == 16:
                type_decl = "i16"
            elif bits == 32:
                type_decl = "i32"
            elif bits == 64:
                type_decl = "i64"
            elif bits <= 8:
                type_decl = "i8"
            elif bits <= 16:
                type_decl = "i16"
            elif bits <= 32:
                type_decl = "i32"
            elif bits <= 64:
                type_decl = "i64"
            else:
                type_decl = f"[i8; {math.ceil(bits / 8)}]"
        else:
            if bits == 8:
                type_decl = "u8"
            elif bits == 16:
                type_decl = "u16"
            elif bits == 32:
                type_decl = "u32"
            elif bits == 64:
                type_decl = "u64"
            elif bits <= 8:
                type_decl = "u8"
            elif bits <= 16:
                type_decl = "u16"
            elif bits <= 32:
                type_decl = "u32"
            elif bits <= 64:
                type_decl = "u64"
            else:
                type_decl = f"[u8; {math.ceil(bits / 8)}]"

        decl = f"pub {ident}: {type_decl},"
        lines.append(f"    {decl:<20} {bit_info}")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Convert bdd pattern JSON to Rust struct definition")
    parser.add_argument("input", nargs="?", default="-", help="Input JSON file or '-' for stdin")
    parser.add_argument("-n", "--name", default="BddPacket", help="Rust struct name (default: BddPacket)")
    args = parser.parse_args()

    if args.input == "-":
        content = sys.stdin.read()
    else:
        with open(args.input, "r", encoding="utf-8") as f:
            content = f.read()

    data = json.loads(content)
    print(generate_rust(data, struct_name=args.name), end="")


if __name__ == "__main__":
    main()
